name: Continuous Deployment to Itch.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy docs folder to Itch.io
        run: butler push ./docs katm6211/d3project:html
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}